// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chwqwteyqzwtrcodvbdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNod3F3dGV5cXp3dHJjb2R2YmR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODI2MDIsImV4cCI6MjA2MzY1ODYwMn0.8Ofq6BbH7I2lo4KXV2YAqbEfEk74z7npqSqIAFRtOfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);